### ISSUE TITLE
Be able to use shell aliases

### ISSUE THREAD

**Issue by HeadlessChild** [markjones112358/dmenu-extended#27] opened 2016-05-25 19:43 UTC
Hi,

Thank you for dmenu-extended, I love it.

Would it be possible to use shell aliases defined in a ~/.zsh_aliases file for dmenu-extended? I use zsh myself but bash would be fine to.

Best regards,
Markus Lindberg.

**Comment by markjones112358** [comment] 2016-06-04 05:16
Hi there,
Sorry it has taken me so long to respond. I've just pushed some changes that should allow you to add a path to your alias file in the preferences and have it added to the menu.
I've also made it possible to set the alias_indicator to an empty character ('') so the aliased items appear in the menu as if they weren't aliased.

In dmenuExtended_preferences.txt set:
    "alias_file": "~/.bash_aliases",
    "indicator_alias": "", 

and rebuild your cache

Please let me know if this is what you were looking for.

Regards,

Mark

**Comment by markjones112358** [comment] 2016-06-04 05:35
Hi again, I just changed
`"alias_file"` to `"path_aliasFile"`
to keep consistency with other paths in the preferences file - so use that instead.

**Comment by HeadlessChild** [comment] 2016-06-04 11:12
Hi,

Thank you so much for taking the effort to implement this.

I have the following in my aliases file:
```
$ cat ~/.zsh_aliases 
alias iamweasle="firefox"
```

And I have added the following to my config (output stripped):
```
$ cat ~/.config/dmenu-extended/config/dmenuExtended_preferences.txt
{
    "path_aliasFile": "~/.bash_aliases",
    "indicator_alias": "",
...
```

But when I try to execute `iamweasle` in `dmenu_extended_run` I get the following:
```
$ dmenu_extended_run
sh: 1: iamweasle: not found
```

I also rebuilt the cache for `dmenu_extended`.

Any ideas? Does it only work with `bash`?

Best regards,
Markus Lindberg

**Comment by markjones112358** [comment] 2016-06-04 20:01
Ah - my bad, sorry about that. Should be fixed now, pull the latest version and try again. What you've got in your preferences file looks good.

-Mark

**Comment by HeadlessChild** [comment] 2016-06-05 00:02
Thank you so much, it works perfectly now. I have tried with both bash and zsh.

I will close this issue/request now. :)

Best regards,
Markus Lindberg

**Comment by HeadlessChild** [comment] 2016-06-08 08:20
Hi again,

I can't seem to get to work on my work computer. I also run zsh shell on this computer. You can see my config file via this gist: [https://gist.github.com/HeadlessChild/37b7af50ec210c97d4593bbfd3c9680b](https://gist.github.com/HeadlessChild/37b7af50ec210c97d4593bbfd3c9680b)

When I try to run an alias command I get the following output:
```
gvfs-open: blackwidow (rdesktop -k sv -g 1200x800 blackwidow -d axis.com -u samarklind > /dev/null 2>&1 &): error opening location: Error when getting information for file '/home/marklind/blackwidow (rdesktop -k sv -g 1200x800 blackwidow -d axis.com -u samarklind > /dev/null 2>&1 &)': No such file or directory
```

It seems like it thinks the alias is a file and not a command.

Best regards
Markus Lindberg

**Comment by markjones112358** [comment] 2016-06-12 04:16
Hi Markus,
I'm having trouble reproducing this error. Could you please show me the corresponding alias in your .zsh_aliases file for this command. At first glance I'm guessing you're trying to run rdesktop to log into axis.com with your username and specify a screen resolution, but I can't see why it's trying to run blackwidow. Is blackwidow supposed to be the alias for the rdesktop command?

-Mark

**Comment by markjones112358** [comment] 2016-07-16 00:10
Closing as unable to reproduce error.

**Closed by markjones112358** 2016-07-16 00:10 UTC
