### ISSUE TITLE
 Ability to view (Aliased) Applications

### ISSUE THREAD

**Issue by lasers** [markjones112358/dmenu-extended#13] opened 2015-01-03 08:13 UTC
I was comparing things and I noticed few missing Applications only to see that it's there (in binary) and it wasn't what I was expecting. I was wondering if that was expected behavior. I was expecting to see "minecraft" and "Minecraft (minecraft)" 

If you have an (aliased) application that execs the same binary. (As the binary itself would...). Both of them will not be in the list ; only the binary will be.

For an exercise....  If you toggled "filter_binaries": true, you're expected to see (aliased) applications. What happened here is that we're seeing a mixed result -- Both (aliased) applications and certain binaries. I think it might be the unintended behavior of omitting / merging two things in your code to display less/repetative results.

**Comment by lasers** [comment] 2015-01-03 09:19
Also, + (plus) - Manually add an entry to the cache... How can I add a directory? I'm trying to do something like "+xdg-open ~/.local/share/Trash # Trash" -- It's not working for me. Perhaps we need a Trash plugin -- or a way to open manually added directories? (/media, /tmp, etc) P.S. I thought you stopped working on dmenu-extended.... I must be using an old version.

**Comment by markjones112358** [comment] 2015-01-03 22:27
Hi Lasers.
I'll explain the intended behaviour first and we'll see if indeed it is misbehaving rather than this being an issue of ambiguous preferences.

1. If an alias exists for an application where that application's binary has the same name as the application - just add the binary. I see no benefit in adding "Minecraft (minecraft)" to the cache where 'minecraft' is equally descriptive.
2. Each item in the cache must have a unique name.

These two work together to do...
minecraft & Minecraft (minecraft) -> minecraft & minecraft -> minecraft

'filter_binaries' is very confusing. In the beginning its purpose was to remove binaries from the cache (e.g. 'cd' and 'ls' etc.) if they were pointless outside of the shell. It aimed to only add a binary if it is associated with an application. Then more thorough application scanning was added along with the 'include_binaries' and 'include_applications'

Does the following configuration produce the cache you're looking for:

    'include_applications': true,
    'include_binaries': false,
    'alias_applications': true

**Comment by markjones112358** [comment] 2015-01-03 23:21
Just pushed a fix for your Trash issue. Try it now.
You should be able to do it with just `+~/.local/share/Trash#Trash`

**Comment by lasers** [comment] 2015-01-03 23:21
Hi Mark,
With the following configuration you provided, I get a minecraft (binary) in the cache where 'minecraft' is equally descriptive. The problem is that I know if I have Applications and Binaries both toggled on and if you merge them, I'm not going to see the whole thing. I do have # Vi Improved (gvim -f) that was apparently added via *.desktop and I want that. I want to see that.

With binaries turned off, I see i3, htop;, xnoise, xfburn, synergy, chromium, mousepad, minecraft, quicksynergy. Those applications had *.desktop and shows up in XFCE Menu.

What's more... I'm confused because I'm seeing lot of Applications that shouldn't be there because they had simple binaries name. I'll list few as I can.

# GTK+ Demo (gtk3-demo)
# Document Viewer (evince)
# About Xfce (xfce4-about)
# Thunar FIle Manager (thunar)
# Firewall Configuration (gufw)
# Log Out (xfce4-session-logout)
# File Manager (thunar)
# Calculator (gnome-calculator)
# Audio Mixer (xfce4-mixer)
# Transmission (transmission-gtk)
# Xfce Terminal (xfce4-terminal)
# Screenshot (xfce4-screenshooter)
# Ristretto Imager Viewer (ristretto)
.... and more.

The above is not listed in order at all. Random picked.

When I do "thunar", I get this. .

thunar                      (It's not there, but with binaries on, I would see it there).
# Thunar File Manager (thunar)
# File Manager (thunar)
# Open Folder with Thunar (thunar)
# Bulk Rename (/usr/lib/Thunar/ThunarBulkRename)
# Removeable Drives and Media (thunar-volman-settings).

Similar to...

minecraft 
Minecraft (minecraft).

The thing is that I sometimes want to view Applications that shows up in the menu (in other DE). If those applications got converted to binaries, I get the impress that Minecraft, Chromium, Xnoise, Xburn, Mousepad, QuickSynergy does not show up in the menu (when I start typing # in dmenu-extended).

**Comment by lasers** [comment] 2015-01-03 23:37
The Trash issue worked right away. Thank you very much. :)

**Comment by lasers** [comment] 2015-01-03 23:47
I think I got confused.

'include_applications': true, 'include_binaries': false, 'alias_applications': true

does not produce minecraft + Minecraft (minecraft) for me.

**Comment by markjones112358** [comment] 2015-01-03 23:48
Great, no problem.
I think I'm going to need a bit of help understanding what you're after in terms of output.
Are you wanting to be able to have everything listed in applications prefixed with the '#' character? If you could provide some examples of your ideal output that might help.

In terms of "simple binaries", it will only shorten to plain binary form if the binary title is **exactly** (case insensitive) the same as the application name. So the fact that you see the results you see is not surprising.

I haven't been able to find a good way of controlling the addition of aliases and binaries into the cache using a minimal set of configuration parameters having obvious names. Hence why it's a bit of a mess.

I hadn't imagined anyone searching by '#' so that's interesting to see the indicator being made use of. If you can think of a more elegant way to control the addition of these elements I'm open to suggestions.

Just saw your last comment. Has this fixed your issue?

**Comment by lasers** [comment] 2015-01-04 00:04
I noticed that I'm unable to remove manually added items. Can you confirm that too? I'm using XFCE panel (w/ menu) because I want to move away from XFCE but I don't like "everything-in-one" binaries (and/or) Applications only dmenu. I hadn't found a lightweight dmenu-like launcher that does lot of things and cover almost everything (including power managment). Basically, a dmenu-like kupfer or GnomeDo.

Adeskmenu came to mind -- but now they rebranded it to a deskbar and it appears broken on i3wm (dual monitors). Pressing # lists Applications and lot of them are missing due to the "simple binaries". I want to unmerge "simple binaries" so I can have everything in the dmenu. This is my issue. I think it would be best not to merge anything and to allow the users to decide how to invoke the dmenu (to find what they're looking for).

I don't know. I think you need more people working on this neat project. Too many launchers came and went by... (GnomeDo for one!). I also found "rebuild cache" when I launch dmenu-extended. I'm not sure if that was intentional. It was just weird to find it there when we have Settings -> Rebuild cache.

**Closed** 2015-01-20 06:05 UTC
